name: documentation

on:
  push:
    branches:
      - master
  pull_request:
    
jobs:
  generate_documentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

#      - name: Setup mdBook
#        uses: peaceiris/actions-mdbook@v1
#        with:
#          mdbook-version: "0.4.5"

#      # This generates the book inside ./book/book
#      - run: mdbook build book

#      # Build the cargo doc and copy it to ./book/book/doc
#      - name: Build the doc
#        run: |
#          cargo doc --no-deps
#          cp -r target/doc book/book/doc
#          echo "<meta http-equiv=refresh content=0;url=pravega_client/index.html>" > book/book/doc/index.html

      - name: Generate Pravega Python API documentation.
        run: |
          pip install 'maturin>=0.14,<0.15' virtualenv pdoc3
          virtualenv venv
          source venv/bin/activate
          maturin develop -m Cargo.toml
          pdoc --html pravega_client
          mkdir -p book/book/python
          cp html/pravega_client/pravega_client.html book/book/python

      - name: Deploy
        uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book/
